apiVersion: apps/v1
kind: Deployment
metadata:
  name: byzantine-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byzantine-operator
  template:
    metadata:
      labels:
        app: byzantine-operator
    spec:
      serviceAccountName: byzantine-operator
      nodeSelector:
        node-role.kubernetes.io/control-plane: "true"
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
      - name: operator
        image: byzantine-detector:v2
        imagePullPolicy: Never
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc:9090"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m" 
          requests:
            memory: "256Mi"
            cpu: "250m"
