apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-crash-loop
  labels:
    app: fault-crash-loop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fault-crash-loop
  template:
    metadata:
      labels:
        app: fault-crash-loop
    spec:
      containers:
      - name: crash-loop
        image: crash-loop-stress:latest
        imagePullPolicy: Never
        command:
        - /bin/sh
        - -c
        - |
          echo "Crash-loop simulation starting..."
          
          echo "Starting normally, will crash in {{CRASH_INTERVAL}} seconds to simulate a crash loop..."
          stress-ng --cpu {{CRASH_WORKERS}} --timeout {{CRASH_INTERVAL-2}}s &
          sleep {{CRASH_INTERVAL}}
          exit 1 # Crash the container
