apiVersion: apps/v1
kind: Deployment
metadata:
  name: fault-cpu-stress
  labels:
    app: fault-cpu-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fault-cpu-stress
  template:
    metadata:
      labels:
        app: fault-cpu-stress
    spec:
      containers:
      - name: stress-ng
        image: polinux/stress-ng
        command:
        - stress-ng
        - --cpu
        - "{{CPU_WORKERS}}"
        - --cpu-load
        - "{{CPU_LOAD}}"
        - --cpu-method
        - "{{CPU_METHOD}}"
        - --timeout
        - "{{DURATION}}"
        - --verbose
      restartPolicy: Always
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "2"
          memory: "256Mi"
