apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-baseline
  labels:
    app: redis-baseline
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-baseline
  template:
    metadata:
      labels:
        app: redis-baseline
    spec:
      # Edge simulation: Redis acts as coordinator (state broker)
      # Run: kubectl label node k3s-wk1 edge-role=coordinator
      nodeSelector:
        edge-role: coordinator
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
      - name: redis-load
        image: redis:alpine
        command:
        - /bin/sh
        - -c
        - |
          echo "Starting Redis workload generator..."

          while true; do

            KEY="key_$RANDOM"
            VALUE="value_$RANDOM"

            # write
            redis-cli -h localhost SET $KEY $VALUE >/dev/null

            # read
            redis-cli -h localhost GET $KEY >/dev/null

            # occasional burst
            if [ $((RANDOM % 5)) -eq 0 ]; then
              for i in $(seq 1 20); do
                redis-cli -h localhost SET burst_$RANDOM data >/dev/null
              done
            fi

            # jittered interval
            sleep $((RANDOM % 3 + 1))

          done

---
apiVersion: v1
kind: Service
metadata:
  name: redis-baseline-svc
spec:
  selector:
    app: redis-baseline
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
