apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-generator
  labels:
    app: traffic-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-generator
  template:
    metadata:
      labels:
        app: traffic-generator
    spec:
      containers:
      - name: hey
        image: devopsfaith/hey:latest
        command:
        - /bin/sh
        - -c
        - |
          while true; do
            # Send traffic to Nginx
            echo "Sending traffic to Nginx..."
            hey -n 200 -c 10 http://nginx-baseline-svc:80/
            
            # Send traffic to API
            echo "Sending traffic to API..."
            hey -n 100 -c 5 http://api-baseline-svc:8080/
            
            sleep 10
          done
