apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-agent
  namespace: default
  labels:
    app: monitor-agent
spec:
  selector:
    matchLabels:
      app: monitor-agent
  template:
    metadata:
      labels:
        app: monitor-agent
    spec:
      containers:
      - name: agent
        image: monitor-agent:v3
        imagePullPolicy: Never
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 50Mi
            cpu: 10m
      terminationGracePeriodSeconds: 30
