# Disable components you don't need
kubeControllerManager:
  enabled: false

kubeProxy:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

# Reduce Prometheus footprint
prometheus:
  prometheusSpec:
    retention: 6h
    scrapeInterval: 30s
    evaluationInterval: 30s
    replicas: 1

    resources:
      requests:
        memory: 400Mi
        cpu: 200m
      limits:
        memory: 700Mi
        cpu: 500m

# Reduce Grafana footprint
grafana:
  resources:
    requests:
      memory: 150Mi
      cpu: 100m
    limits:
      memory: 300Mi
      cpu: 200m

# Alertmanager light config
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        memory: 100Mi
      limits:
        memory: 200Mi

# Node exporter lighter
nodeExporter:
  resources:
    requests:
      memory: 50Mi
    limits:
      memory: 100Mi
